### ISSUE TITLE
Python window appears but game fails to launch

### ISSUE THREAD

**Issue by therealcharmics** [gurrgur/er-patcher#58]
Hello, I have Python 3.9.13 on windows 10, and it does have PATH. 

When installing the mod and launching the game, the python window appears for a moment (blank) and then closes, and the game does not launch. 

Startup commands tested:
python er-patcher --rate 165 --all -- %command%
python er-patcher --all -- %command%
python er-patcher -u -- %command%

Latest version of windows 10 and the game.

**Comment by therealcharmics** [comment]
More information. I tried running it manually and got this error on line 137. 

AttributeError: 'WindowsPath' object has no attribute 'hardlink_to'

I truncated the script and manually copied the modified exe back into the game directory, and can confirm that the rest of it seems to be working.

**Comment by gurrgur** [comment]
Thanks, that information is helpful! Apparently `hardlink_to` has been added only in python 3.10 so no wonder its not working with python 3.9. Hence this is a regression in the latest er-patcher release.

Can you please try replacing line 137 with the following:

``` python
            if sys.version_info.minor >= 10:
                (game_dir_patched / f).hardlink_to(f)
            else:
                f.link_to(game_dir_patched / f)
```

Hope that helps!

**Comment by gurrgur** [comment]
Or just use this:
 
[er-patcher.zip](https://github.com/gurrgur/er-patcher/files/13855723/er-patcher.zip)

**Comment by mizufare** [comment]
> Or just use this:
> 
> [er-patcher.zip](https://github.com/gurrgur/er-patcher/files/13855723/er-patcher.zip)

thanks! that fixed the issue for me (on Arch Linux)
